### ISSUE TITLE
Running without db config gives error

### ISSUE THREAD

**Issue by mwiesweg** [veaceslav/TumorProfil#1]
Running the application with no MariaDB server (neither on the local machine, nor any configured remote) gives an error (Failed to create tables) and quits.
Should 
1) check if there is a connection at all
2) if not, go straight to the config dialog

(or how should I enter the config dialog?)

**Comment by veaceslav** [comment]
The problem was in some faulty sqlite create tables. I fixed them. Also, by default TumorProfil will create a sqlite, then you can go to settings and configure a mysql.
