### ISSUE TITLE
Allow "master config" for db location

### ISSUE THREAD

**Issue by mwiesweg** [veaceslav/TumorProfil#2]
Allow to store a configuration file alongside the binary which gives the database connection parameters except for username / password.
If such a file is found, the relevant settings are used and cannot be changed.
The values read from the file should not be stored locally, instead always read from the file.
Location of the file should be in the same directory as the binary that is run.

**Comment by veaceslav** [comment]
I implemented the default parameters to be read from dbconfig.xml, they can not be read from settings.
The username and password tag is also here but can be left blank.

Is it necessary to lock the parameters? Maybe you want to edit them, just in case ip of database might change.

**Comment by veaceslav** [comment]
Ok, I will close this for now. Open if there is another problem..
