### ISSUE TITLE
Allow to change password from TumorProfil

### ISSUE THREAD

**Issue by mwiesweg** [veaceslav/TumorProfil#4]
Allow to change the current user's db system password from the TumorProfil app.

**Comment by veaceslav** [comment]
User should be allowed to change only his password? Here comes a problem: The user should not only change his password in mysql, but also to update all his encryption keys..

**Comment by mwiesweg** [comment]
Yes, I see the problem.
Is it possible? You see the side effects better than I do.
I would be nice, but if it's a major problem, than we can do without.

**Comment by veaceslav** [comment]
Ok, this is possible to implement but I need to warn you about security implications:
1. I was thinking of giving the non-provileged users read/write access to tumorprofil database and only read access to tumorusers database - the reason: Tumor profil was supposed to read data for authentication
2. If you want to change password from Tumor Profil app: then you need to have read/write access
3. With read/write access an attacker can not retrieve the encryption keys, except his owns, but it can now delete everything, including your admin keys, and you basically are left with undecryptable content in the database.
4. With old approach(described at point 1), somebody can still delete everything in the database, so it is not like we offer less security.

If you still think that you need this, then tell me and I will implement.

**Comment by mwiesweg** [comment]
The threat of deleting everything must be solved by having backups.

So yes, people will want to change the password, it would be really nice to 
have that.

Marcel

**Comment by veaceslav** [comment]
This feature is implemented. Change Password menu can be found in settings. Reopen if you have more suggestions etc..
